apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-aqi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-aqi-app
  template:
    metadata:
      labels:
        app: weather-aqi-app
    spec:
      containers:
        - name: weather-aqi-app
          image: your-docker-repo/weather-aqi-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_WEATHER_API_KEY
              value: "your_openweathermap_api_key"
            - name: REACT_APP_AQI_API_KEY
              value: "your_aqi_api_key"
