
name: Security Suite for Containers (K8s & Containerization)

on:
  push:
    branches:
      - main
# on:
#   workflow_dispatch:

jobs:
  BuildingAppImage:
    runs-on: ubuntu-latest

    steps:
    - name: Get current timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build


    - name: Build Docker image
      run: |
        echo $pwd
        ls
        docker build -t weather-aqi-app:latest .
        docker save weather-aqi-app:latest -o weather-aqi-app.tar

    - name: Run Container Scan
      run: |
        docker pull aquasec/trivy:latest

        docker run aquasec/trivy:latest image --format json --output $GITHUB_WORKSPACE/trivy-report-${{ env.TIMESTAMP }}.json weather-aqi-app:latest

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: weather-aqi-app:latest

    - name: Upload Trivy scan report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy-report-*.json

    - name: Log in to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_SEC }}
    
    - name: Push Container image to GitHub Container Registry
      run: |
        docker tag weather-aqi-app:latest ghcr.io/${{ github.repository_owner }}/weather-aqi-app:latest
        docker push ghcr.io/${{ github.repository_owner }}/weather-aqi-app:latest